[package]
name = "indra"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
lerp = "0.5.0"
rppal = "0.22.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
